### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by simcha-c** [tseleski/JustNote#2]
Hello, 

Here are a few things you should update.

- [x] All the table names should be plural. so instead of `Users` it should be `users`.

**notebooks**
- [x] when you say the `title` will be unique on `user_id`, that should go after the table info.
- [x] any column that is a foreign_keys should be specified in the details.

**notes**
- [x] the content column should be `text` and not `string`. Type `string` will be shorter than `text` and we'll def want the content to be longer.

Everything else looks good! The main thing to fix is styling. That is important since it will make it much more readable.

Great job!
Simcha

**Comment by tseleski** [comment]
Got it!
